### PR TITLE
implemented open_upload_stream

### PR DESCRIPTION
**Pull request by manuelaguirre**

### CODE REVIEW

**Comment by manuelaguirre** [comment]
We should make some tests before merging

**Comment by manuelaguirre** [comment]
I manually tested it and it seems to be working quite well

**Comment by lucsoft** [comment]
oh lol github didn't notify me

**Comment by manuelaguirre** [comment]
tomorrow I might implement `open_upload_stream_with_id` piping like what you did.

**Comment by manuelaguirre** [comment]
You can comment on the code if you want, feedback is appreciated.

**Comment by lucsoft** [comment]
Im half way merging your code and it's already working

**Comment by lucsoft** [comment]
But the problem is that it only works for one chunk

**Comment by lucsoft** [comment]
Okay, it's fixed now. I will now work on the tests now.

Thanks so much 🎉🚀 
I merged the code manual, so I can't really merge this pr correctly

**Pull request closed without merging**
